-- Create the posts table
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instagram_shortcode TEXT NOT NULL UNIQUE,
    status TEXT DEFAULT 'pending',
    category TEXT,
    original_url TEXT,
    posted_at TIMESTAMP WITH TIME ZONE,
    author TEXT,
    content TEXT,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anonymous read access (since you want to display it on the frontend)
CREATE POLICY "Allow public read access"
ON public.posts
FOR SELECT
TO anon
USING (true);

-- Create a policy that allows service_role (backend) to do everything
-- implicitly enabled for service_role usually, but good to be explicit or if using authenticated users
-- For simple API usage with the anon key for read, and secret key for write (if using python SDK with service role), this is fine.
-- If you are using the SAME key for python (which is likely the anon key based on the error), you need to allow insert/update for anon too OR use the SERVICE_ROLE key in the backend.

-- WARNING: If you are using the ANON key in the backend python script, you must allow write access to anon:
-- Since this is an internal tool, allowing anon write (or securing it differently) might be needed if you don't have the service role key.
-- Ideally, use the SERVICE_ROLE key in .env for the backend.
-- Assuming the provided key IS the anon key, we need this for the python script to work:
CREATE POLICY "Allow anon insert/update"
ON public.posts
FOR ALL
TO anon
USING (true)
WITH CHECK (true);
